# defaults for ansible-anaconda
---
# main Anaconda download server
anaconda_mirror : https://repo.continuum.io/archive

# version of python (2|3)
anaconda_python_ver : 3

# anaconda version
anaconda_ver: '4.3.0'

# when downloading the anaconda binary it might take a while
# don't let you less great network connection cause the roll to falter
anaconda_timeout_seconds : 3600

anaconda_checksums :
  quit : sha256:7c52e6e99aabb24a49880130615a48e685da444c3c14eb48d6a65f3313bf745c
  Anaconda3-4.3.0-Linux-x86_64.sh : sha256:e9169c3a5029aa820393ac92704eb9ee0701778a085ca7bdc3c57b388ac1beb6

# add the anaconda python onto the front of your path.
# Caveat Emptor: if your OS package manager is python based careful about jamming it
anaconda_make_sys_default : False

# create link with directory name anaconda  
anaconda_make_link: False

# when installed inside a container delete all of the installer artifacts.
anaconda_cleanup : True

# where to put installation directory
anaconda_parent_dir: /opt

# trigger conda update after installation
anaconda_pkg_update: True

# which packages should be installed first
anaconda_dependencies:
 - bzip2
