# vars file for ansible-rstudio-server
---
rstudio_server_dependencies:
  - curl

rstudio_server_downloads_path: /tmp
rstudio_server_download_cleanup: True

rstudio_server_machine_map:
  i686: i386
  i386: i386
  x86_64: amd64
  amd64: amd64
